CREATE TABLE USERS (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME    VARCHAR2(255) NOT NULL,
    EMAIL       VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD    VARCHAR2(255) NOT NULL, -- 비밀번호 컬럼 추가
    USER_ROLE   VARCHAR2(20) DEFAULT 'USER' CHECK (USER_ROLE IN ('USER', 'ADMIN')),
    EXPERIENCE  VARCHAR2(20) CHECK (EXPERIENCE IN ('beginner', 'intermediate', 'advanced')),
    ASSET       VARCHAR2(20) CHECK (ASSET IN ('stock', 'etf', 'bonds', 'real_estate')),
    GOAL        VARCHAR2(20) CHECK (GOAL IN ('short_term', 'mid_term', 'income')),
    RISK        VARCHAR2(20) CHECK (RISK IN ('conservative', 'neutral', 'aggressive')),
    KNOWLEDGE   VARCHAR2(20) CHECK (KNOWLEDGE IN ('basic', 'intermediate', 'advanced')),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT constraint_name, search_condition
FROM user_constraints
WHERE table_name = 'USERS'
  AND constraint_type = 'C';

ALTER TABLE USERS
DROP CONSTRAINT SYS_C008258;

ALTER TABLE USERS
ADD CONSTRAINT chk_users_experience
CHECK (EXPERIENCE IN ('beginner', 'advanced'));

UPDATE USERS
SET EXPERIENCE = 'beginner'
WHERE EXPERIENCE = 'intermediate';

COMMIT;

CREATE TABLE etf_meta (
    etf_id VARCHAR2(20) PRIMARY KEY,
    name VARCHAR2(100),
    theme VARCHAR2(50),
    asset_type VARCHAR2(20),
    risk_level NUMBER,
    expense_level VARCHAR2(10)
);

-- ETF 일별 시세 정보를 저장하는 테이블
CREATE TABLE ETF_PRICE (
    BAS_DT      VARCHAR2(8),   -- 기준일자 (YYYYMMDD)
    ISIN_CD     VARCHAR2(20),  -- 표준코드 (ISIN)
    ITMS_NM     VARCHAR2(100), -- 종목명
    CLPR        NUMBER,        -- 종가
    VS          NUMBER,        -- 전일대비 등락
    FLUC_RT     NUMBER,        -- 등락률
    MKP         NUMBER,        -- 시가
    HIPR        NUMBER,        -- 고가
    LOPR        NUMBER,        -- 저가
    TR_QUANT    NUMBER,        -- 거래량
    TR_PRC      NUMBER         -- 거래대금
);

-- 데이터 조회 성능 향상을 위한 인덱스 설정
CREATE INDEX IDX_ETF_PRICE_BAS_DT ON ETF_PRICE(BAS_DT);
CREATE INDEX IDX_ETF_PRICE_ISIN_CD ON ETF_PRICE(ISIN_CD);

CREATE TABLE RECOMMENDATIONS (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID     NUMBER NOT NULL,
    ISIN        VARCHAR2(255) NOT NULL,
    SCORE       NUMBER(5), -- 추천 점수
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- 외래 키 설정 (USERS 테이블의 ID 참조)
    CONSTRAINT FK_REC_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 외래 키 조인을 위한 인덱스 생성 (성능 최적화)
CREATE INDEX IDX_REC_USER_ID ON RECOMMENDATIONS(USER_ID);

ALTER TABLE etf_meta
MODIFY theme VARCHAR2(200);

ALTER TABLE ETF_META
ADD ISIN_CD VARCHAR2(20);

UPDATE etf_meta
SET isin_cd = etf_id;


ALTER TABLE ETF_META ADD ISIN_CD VARCHAR2(20);


ALTER TABLE ETF_META DROP PRIMARY KEY;
ALTER TABLE ETF_META ADD CONSTRAINT PK_ETF_META PRIMARY KEY (ISIN_CD);

INSERT INTO USERS (
    USERNAME,
    EMAIL,
    PASSWORD,
    USER_ROLE,
    EXPERIENCE,
    ASSET,
    GOAL,
    RISK,
    KNOWLEDGE
) VALUES (
    'testuser',
    'test@test.com',
    '1234',           -- 나중에 BCrypt로 변경
    'USER',
    'beginner',
    'etf',
    'mid_term',
    'neutral',
    'basic'
);

COMMIT;

SELECT * FROM users;

DELETE FROM USERS WHERE ID = 2;
COMMIT;

SELECT * FROM ETF_META em ;
SELECT * FROM ETF_PRICE ep ;

TRUNCATE TABLE ETF_META;

SELECT DISTINCT theme
FROM ETF_META
ORDER BY theme;

SELECT DISTINCT asset_type
FROM ETF_META
ORDER BY asset_type;

SELECT DISTINCT risk_level
FROM ETF_META
ORDER BY risk_level;

SELECT DISTINCT expense_level
FROM ETF_META
ORDER BY expense_level;

TRUNCATE TABLE ETF_PRICE;

SELECT * FROM ETF_PRICE ep ;

select BAS_DT from ETF_PRICE where ISIN_CD='KR0000390390';

SELECT BAS_DT FROM ETF_PRICE WHERE BAS_DT = '20260102';

SELECT COUNT(*) 
FROM ETF_PRICE 
WHERE ISIN_CD = 'KR0000390390';

SELECT BAS_DT, CLPR 
FROM ETF_PRICE
WHERE ISIN_CD = 'KR0000390390'
ORDER BY BAS_DT
FETCH FIRST 5 ROWS ONLY;

SELECT count(*) FROM ETF_PRICE ep ;

SELECT * FROM ETF_PRICE ep ;

SELECT * FROM ETF_META em where em.ETF_ID = 'KR7005930003';

SELECT * FROM ETF_META em ;

SELECT * FROM USERS u ;

UPDATE USERS u SET USER_ROLE = 'ADMIN' WHERE u.USERNAME = '4444'; 

TRUNCATE TABLE ETF_PRICE;
TRUNCATE TABLE ETF_META;

ALTER TABLE ETF_PRICE MODIFY BAS_DT VARCHAR2(10);

SELECT * FROM ETF_META em WHERE em.ETF_ID = NULL ;

SELECT constraint_name, search_condition 
FROM user_constraints 
WHERE table_name = 'USERS' 
AND constraint_type = 'C';

DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP SEQUENCE BOARD_SEQ; -- 혹시 있으면 지움
COMMIT;

-- 2. 시퀀스(번호표 기계) 생성
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;

-- 3. 게시판 테이블 생성 (오라클 문법 준수)
CREATE TABLE BOARD (
    board_id NUMBER(19,0) PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    content CLOB NOT NULL,
    views NUMBER(10,0) DEFAULT 0,
    created_date TIMESTAMP,
    user_id NUMBER(19,0),
    CONSTRAINT FK_BOARD_USERS FOREIGN KEY (user_id) REFERENCES USERS(id)
);

-- 4. 저장 (필수)
COMMIT;

SELECT * FROM BOARD;

SELECT * FROM users;

CREATE TABLE ETF_TERM (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
    TERM_NAME   VARCHAR2(100)   NOT NULL,
    TERM_DESC   CLOB            NOT NULL,
    CATEGORY    VARCHAR2(50),
    DESCRIPTION VARCHAR2(2000),
    DETAIL      VARCHAR2(4000)
);

ALTER TABLE ETF_TERM
ADD CONSTRAINT UK_ETF_TERM_NAME UNIQUE (TERM_NAME);

SELECT * FROM ETF_PRICE ep ;

CREATE SEQUENCE NOTICE_SEQ START WITH 1 INCREMENT BY 1;

-- 3. 테이블 생성 (수정됨!)
CREATE TABLE NOTICE (
    notice_id NUMBER(19,0) PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    content CLOB NOT NULL,
    views NUMBER(10,0) DEFAULT 0,
    created_date TIMESTAMP,
    user_id NUMBER(19,0),
    CONSTRAINT FK_NOTICE_USER FOREIGN KEY (user_id) REFERENCES USERS(ID)
);

COMMIT;

------------북마크
CREATE TABLE ETF_BOOKMARK (
    ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID    NUMBER NOT NULL,
    ETF_ID     VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



ALTER TABLE ETF_BOOKMARK
ADD CONSTRAINT FK_BOOKMARK_USER
FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;


ALTER TABLE ETF_BOOKMARK
ADD CONSTRAINT UK_USER_ETF_BOOKMARK
UNIQUE (USER_ID, ETF_ID);

COMMIT;

SELECT * FROM etf_bookmark;

-- 1. 좋아요 중간 테이블 생성
CREATE TABLE BOARD_LIKES (
    board_id NUMBER(19,0) NOT NULL,
    user_id NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_BOARD_LIKES PRIMARY KEY (board_id, user_id),
    CONSTRAINT FK_LIKES_BOARD FOREIGN KEY (board_id) REFERENCES BOARD(board_id) ON DELETE CASCADE,
    CONSTRAINT FK_LIKES_USER FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

-- 2. 저장
COMMIT;

-- 2. 이벤트 시퀀스 생성
CREATE SEQUENCE EVENT_SEQ START WITH 1 INCREMENT BY 1;

-- 3. 테이블 생성
CREATE TABLE EVENT (
    event_id NUMBER(19,0) PRIMARY KEY,
    title VARCHAR2(200 CHAR) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    thumbnail_url VARCHAR2(500 CHAR),
    link_url VARCHAR2(500 CHAR),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 4. 데이터 넣기 (TO_DATE로 날짜 형식 강제 지정)
INSERT INTO EVENT (event_id, title, start_date, end_date, thumbnail_url, link_url)
VALUES (EVENT_SEQ.NEXTVAL, '대한민국 ETF 시장 300조 돌파 축하 이벤트🎉', TO_DATE('2026-01-09', 'YYYY-MM-DD'), TO_DATE('2026-01-23', 'YYYY-MM-DD'), 'https://via.placeholder.com/600x300/3e65e4/ffffff?text=ETF+300T', '#');

INSERT INTO EVENT (event_id, title, start_date, end_date, thumbnail_url, link_url)
VALUES (EVENT_SEQ.NEXTVAL, '요즘 대세 국장 대표 ETF 매수 이벤트', TO_DATE('2026-01-05', 'YYYY-MM-DD'), TO_DATE('2026-01-28', 'YYYY-MM-DD'), 'https://via.placeholder.com/600x300/4c8bf5/ffffff?text=KOREA+ETF', '#');

INSERT INTO EVENT (event_id, title, start_date, end_date, thumbnail_url, link_url)
VALUES (EVENT_SEQ.NEXTVAL, 'KODEX 반도체 ETF 매수 이벤트', TO_DATE('2026-01-05', 'YYYY-MM-DD'), TO_DATE('2026-01-28', 'YYYY-MM-DD'), 'https://via.placeholder.com/600x300/e6f4ff/000000?text=Semiconductor', '#');

INSERT INTO EVENT (event_id, title, start_date, end_date, thumbnail_url, link_url)
VALUES (EVENT_SEQ.NEXTVAL, '숏박스와 함께하는 국장투자 이벤트 (종료)', TO_DATE('2025-12-04', 'YYYY-MM-DD'), TO_DATE('2025-12-28', 'YYYY-MM-DD'), 'https://via.placeholder.com/600x300/333333/ffffff?text=ShortBox', '#');

— 5. 저장
COMMIT;

ALTER TABLE USERS MODIFY (
    EXPERIENCE DEFAULT 'beginner',
    ASSET      DEFAULT 'etf',
    GOAL       DEFAULT 'mid_term',
    RISK       DEFAULT 'neutral',
    KNOWLEDGE  DEFAULT 'basic'
);

ALTER TABLE USERS MODIFY (
    EXPERIENCE NOT NULL,
    ASSET      NOT NULL,
    GOAL       NOT NULL,
    RISK       NOT NULL,
    KNOWLEDGE  NOT NULL
);

COMMIT;

SELECT * FROM users;

-- 1. 이규민(ID 2)을 관리자(ADMIN)로 변경
UPDATE USERS 
SET USER_ROLE = 'ADMIN' 
WHERE ID = 2;

-- 2. 변경사항 저장 (필수!)
COMMIT;

-- NOTICE 테이블에 뉴스 관련 컬럼 추가
ALTER TABLE NOTICE ADD ORIGINAL_URL VARCHAR2(1000);
ALTER TABLE NOTICE ADD THUMBNAIL_URL VARCHAR2(1000);

-- 변경사항 저장
COMMIT;

ALTER TABLE ETF_PRICE
ADD CONSTRAINT FK_ETF_PRICE_META
FOREIGN KEY (ISIN_CD)
REFERENCES ETF_META (ISIN_CD);

ALTER TABLE USERS
ADD (
    PROVIDER     VARCHAR2(20),
    PROVIDER_ID  VARCHAR2(100)
);

UPDATE USERS
SET PROVIDER = 'LOCAL'
WHERE PROVIDER IS NULL;

ALTER TABLE USERS
MODIFY PASSWORD NULL;

ALTER TABLE USERS
ADD CONSTRAINT UK_USERS_EMAIL_PROVIDER
UNIQUE (EMAIL, PROVIDER);




-- 1. 전체 데이터 개수 카운트 (이게 2개 이상이어야 함)
SELECT COUNT(*) AS total_count 
FROM etf_price 
WHERE isin_cd = 'KR0000283580';

-- 2. 날짜별로 데이터가 분산되어 있는지 확인 (만약 날짜가 1개만 나오면 계산 불가)
SELECT bas_dt, COUNT(*) 
FROM etf_price 
WHERE isin_cd = 'KR7461340002'
GROUP BY bas_dt
ORDER BY bas_dt ASC;

-- 3. 실제 들어있는 데이터 10개 눈으로 확인
SELECT * FROM etf_meata 
WHERE isin_cd = 'KR0000283580'
ORDER BY bas_dt DESC
FETCH FIRST 10 ROWS ONLY;

SELECT * FROM etf_meta 

TRUNCATE TABLE etf_price;

DROP TABLE etf_term CASCADE CONSTRAINTS;

TRUNCATE TABLE etf_meta;

BEGIN
    -- 20251017 기준으로 과거 100일치 데이터 생성
    FOR i IN 1..100 LOOP
        INSERT INTO etf_price (bas_dt, isin_cd, clpr, vs, fluc_rt, mkp, lopr)
        SELECT 
            TO_CHAR(TO_DATE('20251017', 'YYYYMMDD') - i, 'YYYYMMDD'), -- 날짜 하루씩 빼기
            'KR7461340002', -- 형이 보고 있는 종목 코드로 변경 가능
            27725 - (i * 10) + CASE WHEN MOD(i, 2) = 0 THEN 50 ELSE -50 END, -- 가격 변동
            -515,
            -1.82,
            28240,
            27725 - (i * 10) - 100 -- lopr(저가) 값도 대충 생성
        FROM dual; 
    END LOOP;
    COMMIT;
END;

-- 1. 꼬인 테이블 삭제
DROP TABLE event CASCADE CONSTRAINTS;

-- 2. ★ 테이블 재생성 (날짜 컬럼을 DATE 타입으로 변경) ★
CREATE TABLE event (
    event_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR2(300) NOT NULL,
    start_date    DATE,  -- 🔥 [변경] VARCHAR2 -> DATE
    end_date      DATE,  -- 🔥 [변경] VARCHAR2 -> DATE
    status        VARCHAR2(20),
    thumbnail_url VARCHAR2(500),
    link_url      VARCHAR2(1000),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 3. 데이터 삽입 (문자열을 날짜로 변환해서 넣기: TO_DATE 사용)

-- [1번]
INSERT INTO event (title, start_date, end_date, status, thumbnail_url, link_url)
VALUES (
    'Kodex ETF 증권사 이벤트 안내', 
    TO_DATE('2026-01-01', 'YYYY-MM-DD'), -- 🔥 날짜 형식 변환
    TO_DATE('2026-12-31', 'YYYY-MM-DD'), 
    'ING', 'event-thumbnail1.png', '#'
);

-- [2번]
INSERT INTO event (title, start_date, end_date, status, thumbnail_url, link_url)
VALUES (
    'Kodex 배당맛집 분배금 인증 이벤트', 
    TO_DATE('2026-01-01', 'YYYY-MM-DD'), 
    TO_DATE('2026-12-31', 'YYYY-MM-DD'), 
    'ING', 'event-thumbnail2.png', '#'
);

-- [3번]
INSERT INTO event (title, start_date, end_date, status, thumbnail_url, link_url)
VALUES (
    'TIGER와 함께하는 반도체 투자 이벤트', 
    TO_DATE('2026-01-01', 'YYYY-MM-DD'), 
    TO_DATE('2026-12-31', 'YYYY-MM-DD'), 
    'ING', 'event-thumbnail3.png', '#'
);

-- [4번]
INSERT INTO event (title, start_date, end_date, status, thumbnail_url, link_url)
VALUES (
    'KOSPI 5,000 돌파 기념 이벤트', 
    TO_DATE('2026-01-01', 'YYYY-MM-DD'), 
    TO_DATE('2026-12-31', 'YYYY-MM-DD'), 
    'ENDED', 'event-thumbnail4.png', '#'
);

-- 4. 저장
COMMIT;

-- 1. 기존 테이블 삭제 (새로 만들 때 @Lob이 적용됨)
DROP TABLE NOTICE CASCADE CONSTRAINTS;

-- 1. 혹시 모르니 시퀀스도 없으면 만들어야 함 (있으면 에러 나니까 무시)
CREATE SEQUENCE NOTICE_SEQ_GENERATOR START WITH 1 INCREMENT BY 1;

-- 2. NOTICE 테이블 생성 (Content를 CLOB으로 지정)
CREATE TABLE NOTICE (
    notice_id       NUMBER(19,0) NOT NULL,
    title           VARCHAR2(200 CHAR) NOT NULL,
    content         CLOB NOT NULL,
    original_url    VARCHAR2(255 CHAR),
    thumbnail_url   VARCHAR2(255 CHAR),
    views           INTEGER DEFAULT 0,
    created_date    TIMESTAMP,
    user_id         NUMBER(19,0),
    PRIMARY KEY (notice_id)
);

-- 3. 외래키 연결 (USERS 테이블이랑 연결)
ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_USER FOREIGN KEY (user_id) REFERENCES USERS (id);

COMMIT;