SELECT * FROM dual;
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP USER scott CASCADE;
CREATE USER scott IDENTIFIED BY tiger;
GRANT CONNECT,resource TO scott;
GRANT CREATE VIEW TO scott;
GRANT unlimited TABLESPACE TO scott;