-- 회원가입 SQL (영준)
CREATE TABLE MEMBER (
	NO			NUMBER 		  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	MEMBER_ID 	VARCHAR2(50)  UNIQUE NOT NULL,
	PASSWORD	VARCHAR2(100) NOT NULL,
	NAME 		VARCHAR2(30)  NOT NULL,
	GENDER		CHAR(1) 	  NOT NULL,
	BIRTH_DATE	DATE 		  NOT NULL,
	PHONE		VARCHAR2(20)  NOT NULL,
	ADDRESS		VARCHAR2(300),
	ROLE		VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
	REGDATE		DATE 		  DEFAULT SYSDATE
);
SELECT * FROM MEMBER;
COMMIT;

-- 게시판 공통 테이블(기본 board 게시판 + 사진, 리뷰 게시판)
CREATE TABLE board (
	NO			  NUMBER		CONSTRAINT board_no_pk PRIMARY KEY,
	member_no	  NUMBER		CONSTRAINT board_member_nn NOT NULL,
	board_type	  VARCHAR2(20)  CONSTRAINT board_type_nn NOT NULL,
	restaurant_no NUMBER,
	title		  VARCHAR2(300) CONSTRAINT board_title_nn NOT NULL,
	content		  CLOB			CONSTRAINT board_content_nn NOT NULL,
	rating		  NUMBER(2,1),
	hit			  NUMBER		DEFAULT 0,
	like_count	  NUMBER		DEFAULT 0,
	regdate		  DATE			DEFAULT sysdate,
	update_date	  DATE,
	
	CONSTRAINT board_member_fk
		FOREIGN KEY (member_no) REFERENCES member(NO),
		
	CONSTRAINT board_type_ck
		CHECK (board_type IN ('FREE', 'REVIEW')),
		
	CONSTRAINT board_rating_ck
		CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)
);

-- board 게시판 SEQUENCE
CREATE SEQUENCE board_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999999999
nocache
nocycle;

-- 머릿말 컬럼 추가. 예: 잡담, 질문, 정보 등
ALTER TABLE board ADD category VARCHAR2(20);

-- 평점 항목 3개 추가. 맛, 시설, 서비스
-- 맛 점수 (1.0 ~ 5.0)
ALTER TABLE board ADD taste_rating number(2,1);
-- 시설 점수
ALTER TABLE board ADD facility_rating number(2,1);
-- 서비스 점수
ALTER TABLE board ADD service_rating number(2,1);

-- 기존 rating 컬럼은 "평균 점수" 저장용으로 그대로 사용.

ALTER TABLE board ADD CONSTRAINT board_taste_ck
	CHECK (taste_rating IS NULL OR taste_rating BETWEEN 1 AND 5);
ALTER TABLE board ADD CONSTRAINT board_facility_ck
	CHECK (facility_rating IS NULL OR facility_rating BETWEEN 1 AND 5);
ALTER TABLE board ADD CONSTRAINT board_service_ck
	CHECK (service_rating IS NULL OR service_rating BETWEEN 1 AND 5);

SELECT * FROM board;
COMMIT;

-- 회원 먼저 생성(1번 회원) 후 insert into board 해야 조회 가능
INSERT INTO member (
	member_id,
	password,
	name,
	gender,
	birth_date,
	phone,
	address
) VALUES (
	'test01',
	'1234',
	'테스트회원',
	'M',
	TO_DATE('1994-01-01', 'YYYY-MM-DD'),
	'010-0000-0000',
	'경기도 고양시'
);
SELECT NO, member_id, name FROM MEMBER;

-- 1번 회원 생성 후 진행
INSERT INTO board (
	NO,
	member_no,
	board_type,
	title,
	content
) VALUES (
	board_seq.nextval, 
	1, 
	'FREE', 
	'자유게시판 테스트 제목', 
	'자유게시판 테스트 내용'
);

SELECT * FROM board;
COMMIT;


-- 댓글 테이블
CREATE TABLE board_comment (
	NO			NUMBER			CONSTRAINT board_comment_no_pk PRIMARY KEY,
	board_no	NUMBER			CONSTRAINT board_comment_board_nn NOT NULL,
	member_no	NUMBER			CONSTRAINT board_comment_member_nn NOT NULL,
	content		VARCHAR2(1000)	CONSTRAINT board_comment_content_nn NOT NULL,
	regdate		DATE 			DEFAULT sysdate,
	update_date	DATE,
	
	CONSTRAINT board_comment_board_fk
		FOREIGN KEY (board_no) REFERENCES board(NO)
		ON DELETE CASCADE ,
		
	CONSTRAINT board_comment_member_fk
		FOREIGN KEY (member_no) REFERENCES member(NO)
);
-- update_date 댓글 수정일 / ON DELETE CASCADE 게시글 삭제 시 달린 댓글도 함께 삭제
-- 댓글 번호 시퀀스
CREATE SEQUENCE board_comment_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999999999
nocache
nocycle;

SELECT * FROM board_comment;
COMMIT;

-- 댓글 테이블 INSERT 테스트 / board.NO=3 게시글 필요, member.NO=1 회원 필요
INSERT INTO board_comment(
	NO,
	board_no,
	member_no,
	content
) VALUES (
	board_comment_seq.nextval,
	3,
	1,
	'댓글 테스트 내용입니다.'
);

SELECT * FROM board_comment;
COMMIT;

-- 좋아요 테이블(시퀀스X)
CREATE TABLE board_like (
	board_no	NUMBER CONSTRAINT board_like_board_nn NOT NULL,
	member_no	NUMBER CONSTRAINT board_like_member_nn NOT NULL,
	regdate		DATE   DEFAULT sysdate,
	
	CONSTRAINT board_like_pk
		PRIMARY KEY (board_no, member_no),
		
	CONSTRAINT board_like_board_fk
		FOREIGN KEY (board_no) REFERENCES board(NO)
		ON DELETE CASCADE,
		
	CONSTRAINT board_like_member_fk
		FOREIGN KEY (member_no) REFERENCES member(NO)
);

SELECT * FROM board_like;
COMMIT;

-- 좋아요 INSERT 테스트
INSERT INTO board_like (
	board_no,
	member_no
) VALUES (
	3,
	1
); -- board_like에 좋아요 기록 저장

UPDATE board
SET like_count = like_count + 1
WHERE NO = 3; -- board.like_count 숫자 1 증가

SELECT * FROM board_like;
SELECT * FROM board;

COMMIT;


-- 댓글 + 회원 JOIN 확인 / 작성자 ID, 이름 => member JOIN
SELECT 
	c.NO,
	c.board_no,
	c.content,
	c.regdate,
	m.member_id,
	m.name
FROM board_comment c
JOIN MEMBER m
ON c.member_no = m.NO
WHERE c.board_no = 3
ORDER BY c.NO ASC;

-- 좋아요 확인 JOIN
SELECT
	l.board_no,
	b.title,
	l.member_no,
	m.member_id,
	m.name,
	l.regdate
FROM board_like l
JOIN board b 
ON l.board_no = b.NO 
JOIN MEMBER m 
ON l.member_no = m.NO 
WHERE l.board_no = 3;

COMMIT;

-- 아래는 전부 테스트용 SQL문
SELECT NO, title, rating, update_date, hit FROM board ORDER BY NO DESC;
SELECT * FROM board_comment WHERE board_no = 4;

-- 계산용 테이블
INSERT INTO board (NO, member_no, board_type, category,
				   title, content, hit, like_count, regdate)
SELECT board_seq.NEXTVAL, 1, 'FREE', '잡담',
       '페이징 테스트' || LEVEL, 
       '내용' || LEVEL,
       0, 0, SYSDATE
FROM dual
CONNECT BY LEVEL <= 25;

SELECT * FROM board;

COMMIT;

-- 교차 확인
SELECT b.*, m.member_id, m.name
FROM board b
JOIN MEMBER m ON b.member_no = m.NO
WHERE b.board_type = 'FREE'
ORDER BY b.NO DESC
OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;
-- 화면 페이지 수 = 올림인지 확인
SELECT count(*) FROM board WHERE board_type = 'FREE';