-- 회원가입 SQL (영준)
CREATE TABLE MEMBER(
	NO			NUMBER 		  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	MEMBER_ID 	VARCHAR2(50)  UNIQUE NOT NULL,
	PASSWORD	VARCHAR2(100) NOT NULL,
	NAME 		VARCHAR2(30)  NOT NULL,
	GENDER		CHAR(1) 	  NOT NULL,
	BIRTH_DATE	DATE 		  NOT NULL,
	PHONE		VARCHAR2(20)  NOT NULL,
	ADDRESS		VARCHAR2(300),
	ROLE		VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
	REGDATE		DATE 		  DEFAULT SYSDATE
);
SELECT * FROM MEMBER;
COMMIT;

-- 게시판 공통 테이블(기본 board 게시판 + 사진, 리뷰 게시판)
CREATE TABLE board(
	NO			  NUMBER		CONSTRAINT board_no_pk PRIMARY KEY,
	member_no	  NUMBER		CONSTRAINT board_member_nn NOT NULL,
	board_type	  VARCHAR2(20)  CONSTRAINT board_type_nn NOT NULL,
	restaurant_no NUMBER,
	title		  VARCHAR2(300) CONSTRAINT board_title_nn NOT NULL,
	content		  CLOB			CONSTRAINT board_content_nn NOT NULL,
	rating		  NUMBER(2,1),
	hit			  NUMBER		DEFAULT 0,
	like_count	  NUMBER		DEFAULT 0,
	regdate		  DATE			DEFAULT sysdate,
	update_date	  DATE,
	
	CONSTRAINT board_member_fk
		FOREIGN KEY (member_no) REFERENCES member(NO),
		
	CONSTRAINT board_type_ck
		CHECK (board_type IN ('FREE', 'REVIEW')),
		
	CONSTRAINT board_rating_ck
		CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)
);
SELECT * FROM board;

-- board 게시판 SEQUENCE
CREATE SEQUENCE board_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999999999
nocache
nocycle;

COMMIT;

-- 회원 먼저 생성(1번 회원) 후 insert into board 해야 조회 가능
INSERT INTO member (
	member_id,
	password,
	name,
	gender,
	birth_date,
	phone,
	address
) VALUES (
	'test01',
	'1234',
	'테스트회원',
	'M',
	TO_DATE('1994-01-01', 'YYYY-MM-DD'),
	'010-0000-0000',
	'경기도 고양시'
);
SELECT NO, member_id, name FROM MEMBER;

-- 1번 회원 생성 후 진행
INSERT INTO board (
	NO,
	member_no,
	board_type,
	title,
	content
) VALUES (
	board_seq.nextval, 
	1, 
	'FREE', 
	'자유게시판 테스트 제목', 
	'자유게시판 테스트 내용'
);
SELECT * FROM board;
COMMIT;